#### Handling Imbalance Dataset with Machine Learning

check the data and if dependent variable has high differences like 1 has 1000 records and 0 has 98 , then it is perfect usecase of Imbalance dataset.

For small dataset or huge differece between given class output , can use below technique.

In [ ]:
#pip install imbalanced-learn

In [ ]:
#classification problem
import pandas as pd

df=pd.read_csv('creditcard.csv')
df.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0     0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1     0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2     1 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3     1 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4     2 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642   
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376   
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010   

        V26       V27       V28  Amount  Class  
0 -0.189115  0.133558 -0.021053  149.62    0.0  
1  0.125895 -0.008983  0.014724    2.69    0.0  
2 -0.139097 -0.055353 -0.059752  378.66    0.0  
3 -0.221929  0.062723  0.061458  123.50    0.0  
4  0.502292  0.219422  0.215153   69.99    0.0  

[5 rows x 31 columns]

In [ ]:
df.shape

(140703, 31)

In [ ]:
df.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        1
V6        1
V7        1
V8        1
V9        1
V10       1
V11       1
V12       1
V13       1
V14       1
V15       1
V16       1
V17       1
V18       1
V19       1
V20       1
V21       1
V22       1
V23       1
V24       1
V25       1
V26       1
V27       1
V28       1
Amount    1
Class     1
dtype: int64

In [ ]:
df['Class'].value_counts()  #there is hige difference between two classes so it is not balanced.

Class
0.0    140438
1.0       264
Name: count, dtype: int64

In [ ]:
#independent and dependent dataset
X=df.drop('Class',axis=1)
X=X.dropna(axis=0)
y=df.Class
y=y.dropna(axis=0)

#### Cross validation like KFOLD and Hyperparameter tuning

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
from sklearn.model_selection import KFold
import numpy as np
from sklearn.model_selection import GridSearchCV

In [ ]:
10.0**np.arange(-2,3)

array([1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02])

In [ ]:
log_class=LogisticRegression()
grid={'C':10.0**np.arange(-2,3), 'penalty':['l2']}

cv=KFold(n_splits=5,random_state=None, shuffle=False)  #this is cross validation type

In [ ]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,train_size=0.7)

In [ ]:
clf=GridSearchCV(log_class,grid,cv=cv,n_jobs=-1, scoring='f1_macro') #f1_macro basially used in imbalanced dataset
clf.fit(X_train,y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


GridSearchCV(cv=KFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': array([1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02]),
                         'penalty': ['l2']},
             scoring='f1_macro')

In [ ]:
y_pred=clf.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[42105    31]
 [   34    41]]
0.9984601170311056
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00     42136
         1.0       0.57      0.55      0.56        75

    accuracy                           1.00     42211
   macro avg       0.78      0.77      0.78     42211
weighted avg       1.00      1.00      1.00     42211



In [ ]:
X_train.shape
y_train.value_counts()

Class
0.0    98302
1.0      189
Name: count, dtype: int64

In [ ]:
class_weight=dict({0:1,1:100})  # when two different class has big gap then assign higher weight to class having less number of observations

In [ ]:
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier(class_weight=class_weight)
classifier.fit(X_train,y_train)

RandomForestClassifier(class_weight={0: 1, 1: 100})

In [ ]:
y_pred=clf.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[42105    31]
 [   34    41]]
0.9984601170311056
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00     42136
         1.0       0.57      0.55      0.56        75

    accuracy                           1.00     42211
   macro avg       0.78      0.77      0.78     42211
weighted avg       1.00      1.00      1.00     42211



#### Under sampling
reduce the points of the maximum labels

In [ ]:
y_train.value_counts()

Class
0.0    98302
1.0      189
Name: count, dtype: int64

In [ ]:
from collections import Counter
y_train.value_counts()
Counter(y_train)

Counter({0.0: 98302, 1.0: 189})

In [ ]:
from collections import Counter
from imblearn.under_sampling import NearMiss
ns=NearMiss()
X_train_ns,y_train_ns=ns.fit_resample(X_train,y_train)
print("The number of class before the fit  {}".format(Counter(y_train)))
print("The number of class after the fit  {}".format(Counter(y_train_ns)))

The number of class before the fit  Counter({0.0: 98302, 1.0: 189})
The number of class after the fit  Counter({0.0: 189, 1.0: 189})


In [ ]:
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier(class_weight=class_weight)
classifier.fit(X_train_ns,y_train_ns)

RandomForestClassifier(class_weight={0: 1, 1: 100})

#### Over Sampling

In [ ]:
from imblearn.over_sampling import RandomOverSampler
os=RandomOverSampler(random_state=42)
X_train_ns,y_train_ns=os.fit_resample(X_train,y_train)
print("The number of class before the fit  {}".format(Counter(y_train)))
print("The number of class after the fit  {}".format(Counter(y_train_ns)))

The number of class before the fit  Counter({0.0: 98302, 1.0: 189})
The number of class after the fit  Counter({0.0: 98302, 1.0: 98302})


In [ ]:
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier(class_weight=class_weight)
classifier.fit(X_train_ns,y_train_ns)

RandomForestClassifier(class_weight={0: 1, 1: 100})

In [ ]:
y_pred=clf.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[42105    31]
 [   34    41]]
0.9984601170311056
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00     42136
         1.0       0.57      0.55      0.56        75

    accuracy                           1.00     42211
   macro avg       0.78      0.77      0.78     42211
weighted avg       1.00      1.00      1.00     42211



#### SMOTETomek
based on nearest point it creates more points

In [ ]:
from imblearn.combine import SMOTETomek

In [ ]:
sm=SMOTETomek(random_state=42)
X_train_sm,y_train_sm=sm.fit_resample(X_train,y_train)
print("The number of class before the fit  {}".format(Counter(y_train)))
print("The number of class after the fit  {}".format(Counter(y_train_sm)))

The number of class before the fit  Counter({0.0: 98302, 1.0: 189})
The number of class after the fit  Counter({0.0: 97988, 1.0: 97988})


In [ ]:
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier(class_weight=class_weight)
classifier.fit(X_train_sm,y_train_sm)

RandomForestClassifier(class_weight={0: 1, 1: 100})

In [ ]:
y_pred=clf.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[42105    31]
 [   34    41]]
0.9984601170311056
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00     42136
         1.0       0.57      0.55      0.56        75

    accuracy                           1.00     42211
   macro avg       0.78      0.77      0.78     42211
weighted avg       1.00      1.00      1.00     42211



#### Ensemble Techniques

In [ ]:
from imblearn.ensemble import EasyEnsembleClassifier

In [ ]:
easy=EasyEnsembleClassifier()
easy.fit(X_train, y_train)

EasyEnsembleClassifier()

In [ ]:
y_pred=easy.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[40685  1451]
 [    7    68]]
0.9654592404823388
              precision    recall  f1-score   support

         0.0       1.00      0.97      0.98     42136
         1.0       0.04      0.91      0.09        75

    accuracy                           0.97     42211
   macro avg       0.52      0.94      0.53     42211
weighted avg       1.00      0.97      0.98     42211

